export const guidanceQuotes = [
  "Your present circumstances don't determine where you can go; they merely determine where you start. — Nido Qubein",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "The greatest discovery of all time is that a person can change his future by merely changing his attitude. — Oprah Winfrey",
  "Out of difficulties grow miracles. — Jean de La Bruyère",
  "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
  "Small steps every day lead to big results. — Unknown",
  "Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don't belong. — Mandy Hale",
  "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change. — Unknown",
  "It’s not whether you get knocked down, it’s whether you get up. — Vince Lombardi",
  "Sometimes the smallest step in the right direction ends up being the biggest step of your life. — Naeem Callaway",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. — Joshua J. Marine",
  "Healing takes time, and asking for help is a courageous step. — Mariska Hargitay",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
  "You are braver than you believe, stronger than you seem, and smarter than you think. — A.A. Milne",
  "Every day may not be good... but there’s something good in every day. — Alice Morse Earle",
  "Sometimes we just need someone to simply be there — not to fix anything, but to let us feel we are supported and cared for. — Unknown",
  "If you change the way you look at things, the things you look at change. — Wayne Dyer",
  "Don't be discouraged. It's often the last key in the bunch that opens the lock. — Unknown",
  "Progress, not perfection. — Unknown",
  "Take pride in how far you’ve come. Have faith in how far you can go. — Christian Larson",
];
